### ISSUE TITLE
Crash caused by Redstone bin

### ISSUE THREAD

**Issue by Tsukiyama73** [bigchadguys/SellingBin#1]
As stated, I am experiencing a crash caused by the redstone bin. The exact circumstances are as follows: Placing a redstone selling bin, breaking the bin and picking it back up, then placing it again. The contents of the bin do not seem to matter. This crash also sometimes completely bricks the save making it unplayable.
Minecraft 1.20.1 Fabric 0.16.2 
Here is the crash log
[crash-2024-10-09_08.05.12-server.txt](https://github.com/user-attachments/files/17307762/crash-2024-10-09_08.05.12-server.txt)

(Also, I've never used Git much before, so I hope I didn't mess anything up)

**Comment by UncleSpoods** [comment]
I'm having the same issue as well, with the iron selling bin. Interestingly, it only began happening after I closed the game first the first time since placing the block. I had it running for hours between placing it and closing it, and had no issues, but since loading it the next day, it crashes shortly after loading in. Going to try just breaking the block all together and seeing if it crashes after that.

Edit: After breaking the selling bin, it still crashes after about 5 minutes. No clue why.

**Comment by SimplyFrostii** [comment]
Same issue here, only started happening after the selling bin got placed and the server restarted. From the console messages it appears that something returns a null value after the server autosaves?

![image](https://github.com/user-attachments/assets/68c6b6c7-5ee2-4641-9788-378cea8a53e8)

**Comment by vvlfn** [comment]
Same problem here this time with the diamond selling bin, had to remove the mod from the server and after that even the client because still kept getting crashes.
My crash logs said the same error with null pointers in this.inventory in some function.

**Comment by jflec** [comment]
Fixed with latest
